### ISSUE TITLE
rename `mpl_gui.show`

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/mpl-gui#16]
The name is a good one, but `mpl_gui.show` (which requires a list of `Figures` to be passed) has a very different API than `FigureRegistry.show` (and `mpl_gui.registry.show`) and `matplotlib.pyplot.show` (to which you may not pass a list of Figures).

The current leading contender is `display`

**Comment by jklymak** [comment]
Is it the same idea as "draw" or does it do more than just draw the listed figures?

**Comment by tacaswell** [comment]
It does the actual creation of the GUI elements, puts them on screen, and then spins the event loop.  I went with `display` in #17.
